### ISSUE TITLE
Currency Conversion issue

### ISSUE THREAD

**Issue by rehannali** [techouse/alfred-convert#1]
Hi, I have tried your utility and it worked great but there is problem, it didn't work with all ISO code.

I have asked `conv 1 usd to pkr` or `conv 1 usd pkr` got error. Cannot convert it into PKR.

**Comment by techouse** [comment]
Hi,

As the [NOTES](https://github.com/techouse/alfred-convert#notes) state, all [the reference exchange rates are from the ECB](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html). Unfortunately the PKR is not among them.
