### ISSUE TITLE
Minor Improvement Requests

### ISSUE THREAD

**Issue by jwmann** [techouse/alfred-convert#2]
Love the workflow so far, I came from https://github.com/deanishe/alfred-convert which no longer works for me.
I just have a couple requests, hopefully you find them useful enough to add them.

I love the `home_currency` environment variable but I feel like it would be useful putting it in the configuration section. It would get more visibility since you see the configuration immediately when you install the workflow.

I would also appreciate if there was a configuration for setting the default action to be the copy to clipboard instead of routing to the xe website. Perhaps the action could be a 'Toggle default action' or something similar so that when pressing command, it'll go to the website instead.

Lastly, I was just wondering what server the workflow is connecting to when performing a conversion. I'm unable to see what's inside the workflow binary so I'm not sure where it's connecting and what's it doing exactly. Just some transparency would be nice.

That's all, Thanks again!

**Comment by jwmann** [comment]
I just realized the the 'Copy to clipboard' feature doesn't copy the value to the clipboard. It copies the URL to xe.com.
Is that what it's supposed to be? And if so, can you add that as a feature? I rarely care about xe.com, I just care about the value itself.

**Comment by techouse** [comment]
Hey,

nice to see some people use this 🙈

> I love the `home_currency` environment variable but I feel like it would be useful putting it in the configuration section. It would get more visibility since you see the configuration immediately when you install the workflow.

Good idea 👍 

> I would also appreciate if there was a configuration for setting the default action to be the copy to clipboard instead of routing to the xe website. Perhaps the action could be a 'Toggle default action' or something similar so that when pressing command, it'll go to the website instead.

Perhaps, perhaps I could also use an additional modifier key.

> Lastly, I was just wondering what server the workflow is connecting to when performing a conversion.

Explained in the [README notes](https://github.com/techouse/alfred-convert#notes).

> I'm unable to see what's inside the workflow binary so I'm not sure where it's connecting and what's it doing exactly. Just some transparency would be nice.

What do you mean? You literally stumbled upon the repo that holds the sourcecode 😂 [This](https://github.com/techouse/alfred-convert/blob/v1.0.6/bin/src/services/ecb_exchange_rates.dart) is the service that gets the rates from the ECB.

**Comment by techouse** [comment]
>> I would also appreciate if there was a configuration for setting the default action to be the copy to clipboard instead of routing to the xe website. Perhaps the action could be a 'Toggle default action' or something similar so that when pressing command, it'll go to the website instead.
>
> Perhaps, perhaps I could also use an additional modifier key to do that and keep the original action. 😇

Released now in [v1.0.7](https://github.com/techouse/alfred-convert/releases/tag/v1.0.7)

**Comment by techouse** [comment]
>> I love the home_currency environment variable but I feel like it would be useful putting it in the configuration section. It would get more visibility since you see the configuration immediately when you install the workflow.
>
> Good idea 👍

@jwmann Released now in [v1.1.0](https://github.com/techouse/alfred-convert/releases/tag/v1.1.0). Again, check the readme for more info.

**Comment by jwmann** [comment]
@techouse Thank you so much for adding those for me 🎉 

> > Lastly, I was just wondering what server the workflow is connecting to when performing a conversion.
> 
> Explained in the [README notes](https://github.com/techouse/alfred-convert#notes).
> 
> > I'm unable to see what's inside the workflow binary so I'm not sure where it's connecting and what's it doing exactly. Just some transparency would be nice.
> 
> What do you mean? You literally stumbled upon the repo that holds the sourcecode 😂 [This](https://github.com/techouse/alfred-convert/blob/v1.0.6/bin/src/services/ecb_exchange_rates.dart) is the service that gets the rates from the ECB, specifically the [eurofxref-daily.xml](https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml).

I feel silly, I didn't think you'd put the web server code in this repo as well. Most repos I see only show the alfred code parts that run locally. I appreciate the transparency! :)
 
> > I just realized the the 'Copy to clipboard' feature doesn't copy the value to the clipboard. It copies the URL to xe.com.
> > Is that what it's supposed to be?
> 
> Pretty much, as it holds a URL that's fed to the operating system. The idea of grabbing the value hasn't crossed my mind as the value is more or less indicative and not an actual spot/market value. That's why I decided to send people to Xe.com.

Ah see, I hate to be a bother for something you're doing in your spare time but could you add that as a feature? I do a lot of conversions for estimating costs (roughly) and I will copy and paste the conversion exchange value into my calculations in excel. Putting the value directly in my clipboard on enter would skip a whole bunch of extra steps for me ❤️

**Comment by techouse** [comment]
> I feel silly, I didn't think you'd put the web server code in this repo as well. Most repos I see only show the alfred code parts that run locally. I appreciate the transparency! :)

It's not webserver code. This is all client code.

> Ah see, I hate to be a bother for something you're doing in your spare time but could you add that as a feature?

Done already in 1.0.7 :) Simply use <key>cmd+enter</key>, as the readme says.

**Comment by jwmann** [comment]
@techouse I should've tested it beforehand 😅 You're right, it works great thank you! :) 🎉
